CREATE TABLE CARRO(
	ID_CARRO INT IDENTITY(1,1) NOT NULL,
	ANO INT NOT NULL,
	COR VARCHAR(20) NOT NULL,
	KM VARCHAR(20) NOT NULL,
	ID_MODELO INT,

	CONSTRAINT PK_CARRO_ID PRIMARY KEY (ID_CARRO),
	CONSTRAINT FK_CARRO_ID_MODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID_MODELO)
);

CREATE TABLE CARRO_REVISAO(
	ID_REVISAO INT,
	ID_CARRO INT

	CONSTRAINT PK_CARRO_REVISAO PRIMARY KEY CLUSTERED (ID_REVISAO, ID_CARRO)

);

CREATE TABLE REVISAO(
	ID_REVISAO INT IDENTITY(1,1) NOT NULL,
	DATA DATETIME NOT NULL,
	FILTRO_AR BIT NULL,
	FILTRO_OLEO BIT NULL,
	FREIO BIT NULL,
	CORREIA_DENTADA BIT NULL,
	ALINHAMENTO BIT NULL,
	FILTRO_COMBUSTIVEL BIT NULL,
	VELAS BIT NULL,
	AMORTECEDOR BIT NULL,
	CORREIA_ALTERNADOR BIT NULL,
	FLUIDO_DIRECAO BIT NULL,
	FILTRO_AR_CONDICIONADO BIT NULL,
	LUZES BIT NULL,
	PNEU BIT NULL,
	MOTOR BIT NULL,
	FLUIDO_OLEO BIT NULL,

	CONSTRAINT PK_REVISAO_ID PRIMARY KEY (ID_REVISAO)
);

CREATE TABLE ENDERECO(
	ID_END INT IDENTITY(1,1) NOT NULL,
	RUA VARCHAR(40) NOT NULL,
	NUMERO INT NOT NULL,
	BAIRRO VARCHAR(40) NOT NULL,
	CEP VARCHAR(20) NOT NULL,
	CIDADE VARCHAR(40) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	PAIS VARCHAR(40) NOT NULL


	CONSTRAINT PK_ENDERECO_ID PRIMARY KEY (ID_END)
);

CREATE TABLE MENSAGEM(
	ID_MENSAGEM INT IDENTITY(1,1) NOT NULL,
	TITULO VARCHAR(30) NOT NULL,
	TEXTO_MSG VARCHAR(500) NOT NULL,

	CONSTRAINT PK_MENSAGEM_ID PRIMARY KEY (ID_MENSAGEM)
);

CREATE TABLE MODELO(
	ID_MODELO INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	ID_MONTADORA INT,

	CONSTRAINT PK_MODELO_ID PRIMARY KEY(ID_MODELO),
	CONSTRAINT FK_MODELO_ID_MONTADORA FOREIGN KEY (ID_MONTADORA) REFERENCES MONTADORA(ID_MONTADORA)
);

CREATE TABLE MONTADORA(
	ID_MONTADORA INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(30) NOT NULL,

	CONSTRAINT PK_MONTADORA_ID PRIMARY KEY(ID_MONTADORA)
);

CREATE TABLE CLIENTE(
	ID_USER INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50) NULL,
	SOBRENOME VARCHAR(50) NULL,
	RG VARCHAR(20) NULL,
	CPF VARCHAR(20) NULL,
	DATA_NASC DATETIME NULL,
	EMAIL VARCHAR(40) NOT NULL,
	EMAIL_ALT VARCHAR (40) NULL,
	SEXO VARCHAR(1) NULL,
	TEL_FIX INT NULL,
	TEL_CEL INT NULL,
	TEL_COM INT NULL,
	SENHA VARCHAR(20) NOT NULL,
	USUARIO VARCHAR(20) NOT NULL,
	ID_END INT,
	ID_MENSAGEM INT,
	ID_CARRO INT,


	CONSTRAINT PK_CLIENTE_ID PRIMARY KEY (ID_USER),
	CONSTRAINT FK_CLIENTE_ID_ENDERECO FOREIGN KEY (ID_END) REFERENCES ENDERECO(ID_END),
	CONSTRAINT FK_CLIENTE_ID_MENSAGEM FOREIGN KEY (ID_MENSAGEM) REFERENCES MENSAGEM(ID_MENSAGEM),
	CONSTRAINT FK_CLIENTE_ID_CARRO FOREIGN KEY (ID_CARRO) REFERENCES CARRO(ID_CARRO),
);

CREATE TABLE FUNCIONARIO(
	ID_FUNC INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	USUARIO VARCHAR(30) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	TIPO_USER VARCHAR(20) NOT NULL,
	ATIVO BIT NULL,

	CONSTRAINT PK_FUNCIONARIO_ID PRIMARY KEY(ID_FUNC)
);



